name: flutter_opus
description: A Flutter plugin for Opus audio codec encoding and decoding using FFI.
repository: https://github.com/justin-chen-labs/flutter-opus
issue_tracker: https://github.com/justin-chen-labs/flutter-opus/issues
homepage: https://github.com/justin-chen-labs/flutter-opus
version: 1.0.1

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cj.flutter_opus
        pluginClass: FlutterOpusPlugin
        ffiPlugin: true
      ios:
        pluginClass: FlutterOpusPlugin
        ffiPlugin: true
  
