const int OPUS_OK = 0;
const int OPUS_APPLICATION_VOIP = 2048;
const int OPUS_APPLICATION_AUDIO = 2049;
const int OPUS_SET_BITRATE_REQUEST = 4002;
const int OPUS_SET_COMPLEXITY_REQUEST = 4010;
const int OPUS_SET_DTX_REQUEST = 4016;
